
import { Project, TaskArea, Milestone } from './types';

// Helper to format currency
const formatCurrency = (value: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', minimumFractionDigits: 0, maximumFractionDigits: 0 }).format(value);

const mockProjects: Omit<Project, 'lastUpdatedOn' | 'budget' | 'lastSummaryNotes' | 'rawData'>[] = [
  {
    id: 1,
    projectName: 'Metairie Building',
    status: 'At Risk',
    progressOverall: 35,
    budgetTotal: 5500000,
    budgetUsed: 1925000,
    dueDate: '2025-10-20',
    projectManager: 'Elia Brodsky',
    linkToProjectPlan: '#',
    meetingLink: '#',
  },
  {
    id: 2,
    projectName: 'Ochsner - Four Clinics',
    status: 'At Risk',
    progressOverall: 50,
    budgetTotal: 1320000,
    budgetUsed: 660000,
    dueDate: '2025-06-15',
    projectManager: 'Elia Brodsky',
    linkToProjectPlan: '#',
    meetingLink: '#',
  },
  {
    id: 3,
    projectName: 'Florida Parishes - One Clinic',
    status: 'At Risk',
    progressOverall: 20,
    budgetTotal: 330000,
    budgetUsed: 66000,
    dueDate: '2025-02-28',
    projectManager: 'Elia Brodsky',
    linkToProjectPlan: '#',
    meetingLink: '#',
  },
  {
    id: 4,
    projectName: 'LA Medical Bus',
    status: 'At Risk',
    progressOverall: 60,
    budgetTotal: 350000,
    budgetUsed: 210000,
    dueDate: '2024-12-31',
    projectManager: 'Elise Bordson',
    linkToProjectPlan: '#',
    meetingLink: '#',
  },
  {
    id: 5,
    projectName: 'Residency Housing',
    status: 'On Track',
    progressOverall: 75,
    budgetTotal: 550000,
    budgetUsed: 412500,
    dueDate: '2025-04-30',
    projectManager: 'Nelson Lemieux',
    linkToProjectPlan: '#',
    meetingLink: '#',
  },
  {
    id: 6,
    projectName: 'Parking Structure',
    status: 'On Track',
    progressOverall: 85,
    budgetTotal: 660000,
    budgetUsed: 561000,
    dueDate: '2024-11-30',
    projectManager: 'Elise Bordson',
    linkToProjectPlan: '#',
    meetingLink: '#',
  },
  {
    id: 7,
    projectName: 'AR Renovations',
    status: 'On Track',
    progressOverall: 95,
    budgetTotal: 55000,
    budgetUsed: 52250,
    dueDate: '2024-09-30',
    projectManager: 'Lisa Gage',
    linkToProjectPlan: '#',
    meetingLink: '#',
  },
  {
    id: 8,
    projectName: 'AR New Build',
    status: 'On Track',
    progressOverall: 45,
    budgetTotal: 1650000,
    budgetUsed: 742500,
    dueDate: '2026-01-15',
    projectManager: 'Elia Brodsky',
    linkToProjectPlan: '#',
    meetingLink: '#',
  },
  {
    id: 9,
    projectName: 'Food Pantry Program',
    status: 'On Track',
    progressOverall: 65,
    budgetTotal: 660000,
    budgetUsed: 429000,
    dueDate: '2025-07-22',
    projectManager: 'Nelson Lemieux',
    linkToProjectPlan: '#',
    meetingLink: '#',
  },
  {
    id: 10,
    projectName: 'MedExcel - St. C Repairs',
    status: 'Delayed',
    progressOverall: 25,
    budgetTotal: 422000,
    budgetUsed: 105500,
    dueDate: '2025-09-10',
    projectManager: 'Elise Bordson',
    linkToProjectPlan: '#',
    meetingLink: '#',
  },
  {
    id: 11,
    projectName: 'MedExcel - Carrollton Repairs',
    status: 'Delayed',
    progressOverall: 30,
    budgetTotal: 215000,
    budgetUsed: 64500,
    dueDate: '2025-08-01',
    projectManager: 'Elise Bordson',
    linkToProjectPlan: '#',
    meetingLink: '#',
  },
  {
    id: 12,
    projectName: 'MedExcel - AR Banks & Admin Building',
    status: 'Delayed',
    progressOverall: 15,
    budgetTotal: 24500,
    budgetUsed: 3675,
    dueDate: '2025-03-12',
    projectManager: 'Elise Bordson',
    linkToProjectPlan: '#',
    meetingLink: '#',
  },
  {
    id: 13,
    projectName: 'MedExcel - AR Major Requests',
    status: 'Delayed',
    progressOverall: 10,
    budgetTotal: 51600,
    budgetUsed: 5160,
    dueDate: '2025-11-05',
    projectManager: 'Elise Bordson',
    linkToProjectPlan: '#',
    meetingLink: '#',
  },
  {
    id: 14,
    projectName: 'Pioneer for QS1',
    status: 'On Track',
    progressOverall: 10,
    budgetTotal: 0,
    budgetUsed: 0,
    dueDate: '2026-06-01',
    projectManager: 'Nelson Lemieux',
    linkToProjectPlan: '#',
    meetingLink: '#',
  },
  {
    id: 15,
    projectName: 'Compulink for Optometry',
    status: 'On Track',
    progressOverall: 5,
    budgetTotal: 0,
    budgetUsed: 0,
    dueDate: '2026-07-01',
    projectManager: 'Nelson Lemieux',
    linkToProjectPlan: '#',
    meetingLink: '#',
  },
  {
    id: 16,
    projectName: 'CHW Space in H3C',
    status: 'On Track',
    progressOverall: 5,
    budgetTotal: 0,
    budgetUsed: 0,
    dueDate: '2026-08-01',
    projectManager: 'Nelson Lemieux',
    linkToProjectPlan: '#',
    meetingLink: '#',
  },
  {
    id: 17,
    projectName: 'Data Infrastructure Upgrade',
    status: 'On Track',
    progressOverall: 15,
    budgetTotal: 0,
    budgetUsed: 0,
    dueDate: '2026-02-01',
    projectManager: 'Nelson Lemieux',
    linkToProjectPlan: '#',
    meetingLink: '#',
  },
  {
    id: 18,
    projectName: 'New Imaging System',
    status: 'On Track',
    progressOverall: 10,
    budgetTotal: 0,
    budgetUsed: 0,
    dueDate: '2026-04-01',
    projectManager: 'Nelson Lemieux',
    linkToProjectPlan: '#',
    meetingLink: '#',
  },
  {
    id: 19,
    projectName: 'Occupational Health Initiative',
    status: 'On Track',
    progressOverall: 5,
    budgetTotal: 0,
    budgetUsed: 0,
    dueDate: '2026-05-01',
    projectManager: 'Elia Brodsky',
    linkToProjectPlan: '#',
    meetingLink: '#',
  },
  {
    id: 20,
    projectName: 'Urgent Care Center Setup',
    status: 'On Track',
    progressOverall: 10,
    budgetTotal: 0,
    budgetUsed: 0,
    dueDate: '2025-12-01',
    projectManager: 'Elia Brodsky',
    linkToProjectPlan: '#',
    meetingLink: '#',
  },
  {
    id: 21,
    projectName: 'Kenner Building Renovation',
    status: 'On Track',
    progressOverall: 5,
    budgetTotal: 0,
    budgetUsed: 0,
    dueDate: '2026-09-01',
    projectManager: 'Nelson Lemieux',
    linkToProjectPlan: '#',
    meetingLink: '#',
  },
  {
    id: 22,
    projectName: 'Pathways Program',
    status: 'On Track',
    progressOverall: 10,
    budgetTotal: 0,
    budgetUsed: 0,
    dueDate: '2026-10-01',
    projectManager: 'Nelson Lemieux',
    linkToProjectPlan: '#',
    meetingLink: '#',
  },
  {
    id: 23,
    projectName: 'Senior Services Expansion',
    status: 'On Track',
    progressOverall: 5,
    budgetTotal: 0,
    budgetUsed: 0,
    dueDate: '2026-11-01',
    projectManager: 'Elia Brodsky',
    linkToProjectPlan: '#',
    meetingLink: '#',
  },
  {
    id: 24,
    projectName: 'SOAR Program Implementation',
    status: 'On Track',
    progressOverall: 5,
    budgetTotal: 0,
    budgetUsed: 0,
    dueDate: '2026-12-01',
    projectManager: 'Matthew Case',
    linkToProjectPlan: '#',
    meetingLink: '#',
  },
];

export const PROJECTS: Project[] = mockProjects.map(p => ({
  ...p,
  lastUpdatedOn: new Date().toLocaleDateString(),
  budget: formatCurrency(p.budgetTotal || 0),
  lastSummaryNotes: 'This is a mock project summary from constants.ts.',
  rawData: [],
}));


export const TASK_AREAS: TaskArea[] = [
  { id: 1, name: 'Planning', owner: 'Monique Larrieu', progress: 90, status: 'On Track', issues: 0 },
  { id: 2, name: 'Admin & Governance', owner: 'Frank Folino', progress: 75, status: 'On Track', issues: 1 },
  { id: 3, name: 'Accounting, Finance & Billing', owner: 'Elise Bordson', progress: 60, status: 'Needs Attention', issues: 2 },
  { id: 4, name: 'Clinical Quality', owner: 'Dr. R Post & C White', progress: 80, status: 'On Track', issues: 0 },
  { id: 5, name: 'Operations', owner: 'Jonathan Daniel', progress: 55, status: 'Needs Attention', issues: 3 },
  { id: 6, name: 'Human Resources', owner: 'Andrew Dolan', progress: 95, status: 'On Track', issues: 0 },
  { id: 7, name: 'Facilities', owner: 'Julie Firstly', progress: 70, status: 'On Track', issues: 1 },
  { id: 8, name: 'Marketing & Comms', owner: 'Harold Clark', progress: 85, status: 'On Track', issues: 0 },
  { id: 9, name: 'Technology / IT', owner: 'Michael Harrison', progress: 40, status: 'Blocked', issues: 4 },
  { id: 10, name: 'Credentialing', owner: 'Wendy Rios-Wood', progress: 100, status: 'On Track', issues: 0 },
];

export const MILESTONES: Milestone[] = [
    { id: 1, title: 'Phase 1 Completion', date: '2024-08-30', type: 'Phase Gate', status: 'Upcoming' },
    { id: 2, title: 'Budget Review Q3', date: '2024-09-15', type: 'Reporting', status: 'Upcoming' },
    { id: 3, title: 'Core System Go-Live', date: '2024-11-01', type: 'Key Deliverable', status: 'Upcoming' },
    { id: 4, title: 'Architectural Blueprints', date: '2024-07-20', type: 'Key Deliverable', status: 'Completed' },
    { id: 5, title: 'Stakeholder Meeting', date: '2024-10-05', type: 'Reporting', status: 'Upcoming' },
];
